create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,email text,full_name text,role text not null default 'teacher' check(role in('teacher','admin','student')),created_at timestamptz default now());
create table if not exists public.courses(id uuid primary key default gen_random_uuid(),course_code text unique not null,course_name text not null,credits numeric default 0,is_active boolean default true,created_at timestamptz default now());
create table if not exists public.teacher_courses(teacher_id uuid references public.profiles(id) on delete cascade,course_id uuid references public.courses(id) on delete cascade,primary key(teacher_id,course_id));
create table if not exists public.topics(id uuid primary key default gen_random_uuid(),course_id uuid references public.courses(id) on delete cascade,topic_code text,topic_name text not null,is_active boolean default true);
create table if not exists public.questions(id uuid primary key default gen_random_uuid(),question_code text unique not null,course_id uuid references public.courses(id) on delete cascade,topic_id uuid references public.topics(id) on delete set null,question_text text not null,option_a text not null,option_b text not null,option_c text not null,option_d text not null,correct_option text check(correct_option in('A','B','C','D')) not null,points numeric(8,2) default 1,category text,difficulty text,is_active boolean default true,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.exams(id uuid primary key default gen_random_uuid(),exam_code text unique not null,course_id uuid references public.courses(id) on delete cascade,exam_name text not null,duration_minutes int check(duration_minutes>0),total_questions int default 0,total_points numeric(8,2) default 0,shuffle_questions boolean default true,shuffle_options boolean default true,show_result boolean default true,status text default 'DRAFT' check(status in('DRAFT','OPEN','CLOSED')),created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.exam_questions(id uuid primary key default gen_random_uuid(),exam_id uuid references public.exams(id) on delete cascade,question_id uuid references public.questions(id) on delete cascade,question_order int not null,points numeric(8,2) default 1,is_active boolean default true,created_at timestamptz default now(),unique(exam_id,question_id));
create index if not exists idx_q_course on public.questions(course_id,is_active);
create index if not exists idx_eq_exam on public.exam_questions(exam_id,question_order);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id,email,full_name) values(new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name','')) on conflict(id) do update set email=excluded.email; return new; end;$$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create or replace function public.next_exam_code() returns text language plpgsql as $$declare n int;begin select coalesce(max(substring(exam_code from 3)::int),0)+1 into n from public.exams where exam_code~'^EX[0-9]+$';return 'EX'||lpad(n::text,3,'0');end;$$;
create or replace function public.get_course_stats(p_course_id uuid) returns jsonb language sql security definer set search_path=public as $$select jsonb_build_object('question_count',(select count(*) from questions where course_id=p_course_id and is_active),'topic_count',(select count(*) from topics where course_id=p_course_id and is_active),'class_count',0,'exam_count',(select count(*) from exams where course_id=p_course_id));$$;
create or replace function public.create_exam(p_course_id uuid,p_exam_name text,p_duration_minutes int,p_shuffle_questions boolean default true,p_shuffle_options boolean default true,p_show_result boolean default true) returns jsonb language plpgsql security definer set search_path=public as $$declare r public.exams;begin insert into exams(exam_code,course_id,exam_name,duration_minutes,shuffle_questions,shuffle_options,show_result) values(next_exam_code(),p_course_id,btrim(p_exam_name),p_duration_minutes,p_shuffle_questions,p_shuffle_options,p_show_result)returning * into r;return jsonb_build_object('success',true,'exam',to_jsonb(r));end;$$;
create or replace function public.get_exam_editor(p_exam_id uuid) returns jsonb language sql security definer set search_path=public as $$select jsonb_build_object('exam',to_jsonb(e),'questions',coalesce((select jsonb_agg(jsonb_build_object('exam_question_id',eq.id,'question_id',q.id,'question_code',q.question_code,'question_order',eq.question_order,'points',eq.points,'question_text',q.question_text) order by eq.question_order) from exam_questions eq join questions q on q.id=eq.question_id where eq.exam_id=e.id and eq.is_active),'[]'::jsonb)) from exams e where e.id=p_exam_id;$$;
create or replace function public.get_available_questions(p_exam_id uuid,p_page int default 1,p_page_size int default 20,p_search text default '') returns jsonb language plpgsql security definer set search_path=public as $$declare c uuid;t int;d jsonb;begin select course_id into c from exams where id=p_exam_id;select count(*) into t from questions q where q.course_id=c and q.is_active and not exists(select 1 from exam_questions eq where eq.exam_id=p_exam_id and eq.question_id=q.id and eq.is_active) and(p_search='' or q.question_text ilike '%'||p_search||'%');select coalesce(jsonb_agg(to_jsonb(x)),'[]'::jsonb)into d from(select id,question_code,question_text,points,difficulty from questions q where q.course_id=c and q.is_active and not exists(select 1 from exam_questions eq where eq.exam_id=p_exam_id and eq.question_id=q.id and eq.is_active) and(p_search='' or q.question_text ilike '%'||p_search||'%')order by question_code offset greatest(p_page-1,0)*p_page_size limit p_page_size)x;return jsonb_build_object('data',d,'total',t,'page',p_page,'page_size',p_page_size);end;$$;
create or replace function public.add_questions_to_exam(p_exam_id uuid,p_question_ids uuid[]) returns jsonb language plpgsql security definer set search_path=public as $$declare c uuid;n int:=0;qid uuid;o int;begin select course_id into c from exams where id=p_exam_id;select coalesce(max(question_order),0)into o from exam_questions where exam_id=p_exam_id and is_active;foreach qid in array p_question_ids loop if exists(select 1 from questions where id=qid and course_id=c and is_active) and not exists(select 1 from exam_questions where exam_id=p_exam_id and question_id=qid)then o:=o+1;insert into exam_questions(exam_id,question_id,question_order,points)select p_exam_id,id,o,points from questions where id=qid;n:=n+1;end if;end loop;update exams e set total_questions=(select count(*) from exam_questions where exam_id=e.id and is_active),total_points=coalesce((select sum(points)from exam_questions where exam_id=e.id and is_active),0),updated_at=now()where id=p_exam_id;return jsonb_build_object('success',true,'added',n);end;$$;
create or replace function public.remove_question_from_exam(p_exam_question_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$declare e uuid;begin update exam_questions set is_active=false where id=p_exam_question_id returning exam_id into e;update exams x set total_questions=(select count(*)from exam_questions where exam_id=x.id and is_active),total_points=coalesce((select sum(points)from exam_questions where exam_id=x.id and is_active),0),updated_at=now()where id=e;return jsonb_build_object('success',true);end;$$;

alter table profiles enable row level security;alter table courses enable row level security;alter table teacher_courses enable row level security;alter table topics enable row level security;alter table questions enable row level security;alter table exams enable row level security;alter table exam_questions enable row level security;
create policy "profile self" on profiles for select to authenticated using(id=auth.uid());
create policy "course access" on courses for select to authenticated using(exists(select 1 from teacher_courses t where t.teacher_id=auth.uid() and t.course_id=courses.id) or exists(select 1 from profiles p where p.id=auth.uid() and p.role='admin'));
create policy "topic access" on topics for select to authenticated using(exists(select 1 from teacher_courses t where t.teacher_id=auth.uid() and t.course_id=topics.course_id) or exists(select 1 from profiles p where p.id=auth.uid() and p.role='admin'));
create policy "question access" on questions for all to authenticated using(exists(select 1 from teacher_courses t where t.teacher_id=auth.uid() and t.course_id=questions.course_id) or exists(select 1 from profiles p where p.id=auth.uid() and p.role='admin')) with check(exists(select 1 from teacher_courses t where t.teacher_id=auth.uid() and t.course_id=questions.course_id) or exists(select 1 from profiles p where p.id=auth.uid() and p.role='admin'));
create policy "exam access" on exams for all to authenticated using(exists(select 1 from teacher_courses t where t.teacher_id=auth.uid() and t.course_id=exams.course_id) or exists(select 1 from profiles p where p.id=auth.uid() and p.role='admin')) with check(exists(select 1 from teacher_courses t where t.teacher_id=auth.uid() and t.course_id=exams.course_id) or exists(select 1 from profiles p where p.id=auth.uid() and p.role='admin'));
create policy "exam question access" on exam_questions for all to authenticated using(exists(select 1 from exams e join teacher_courses t on t.course_id=e.course_id where e.id=exam_questions.exam_id and t.teacher_id=auth.uid()) or exists(select 1 from profiles p where p.id=auth.uid() and p.role='admin')) with check(exists(select 1 from exams e join teacher_courses t on t.course_id=e.course_id where e.id=exam_questions.exam_id and t.teacher_id=auth.uid()) or exists(select 1 from profiles p where p.id=auth.uid() and p.role='admin'));

grant execute on function public.get_course_stats(uuid) to authenticated;
grant execute on function public.create_exam(uuid,text,int,boolean,boolean,boolean) to authenticated;
grant execute on function public.get_exam_editor(uuid) to authenticated;
grant execute on function public.get_available_questions(uuid,int,int,text) to authenticated;
grant execute on function public.add_questions_to_exam(uuid,uuid[]) to authenticated;
grant execute on function public.remove_question_from_exam(uuid) to authenticated;

insert into courses(course_code,course_name,credits) values('HP001','Đại cương Sinh thái học',3) on conflict(course_code)do nothing;
insert into topics(course_id,topic_code,topic_name)select id,'SH01','Đại cương Sinh thái học'from courses where course_code='HP001' and not exists(select 1 from topics where course_id=courses.id and topic_code='SH01');
